name = "FactoredElementFunction"
uuid = "42b1b709-83ca-446f-9bcc-67afba14f5e0"
authors = ["Gustavo Goretkin <gustavo.goretkin@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
